### ISSUE TITLE
Hỏi về vấn đề Tokenize câu

### ISSUE THREAD

**Issue by MLlove0402** [trituenhantaoio/vn-bert-base-uncased#1]
Chào anh
Anh cho em hỏi là model của mình tại sao khi Tokennize câu thì lại mất hết thanh sắc vậy ạ,
Ví dụ: xuất sắc -> ["xuat", "sac"] thay vì ["xuất", "sắc"]

**Comment by trituenhantaoio** [comment]
Cảm ơn em, em có thể dùng phiên bản giữ nguyên dấu của tiếng Việt [tại đây](https://huggingface.co/trituenhantaoio/bert-base-vietnamese-diacritics-uncased) nhé!

**Comment by anonymousz97** [comment]
Chào anh, bản kia e thấy khi tokenize ra vẫn là không dấu ? Bên mình có tác động gì đến repo ko ạ?
